export const BRICK_WIDTH = 60;
export const BRICK_HEIGHT = 30;
export const BRICK_SPACING = 3;
export const NUM_ROWS = 30;
export const NUM_COLS = 13;
export const ROWS = NUM_ROWS * BRICK_HEIGHT;
export const COLS = NUM_COLS * BRICK_WIDTH;
export const PLAYER_WIDTH = 100;
export const PLAYER_HEIGHT = 20;
export const PLAYER_LIVES = 2;
export const PLAYER_SPEED = 8;
export const PLAYER_SIDESIZE = 15;
export const BALL_SIZE = 6;
export const BALL_SPEED = 6;

console.assert(BRICK_HEIGHT >= BALL_SIZE, "The brick height can not be smaller than the ball size.");
console.assert(BRICK_WIDTH >= BALL_SIZE, "The brick width can not be smaller than the ball size.");
console.assert(PLAYER_HEIGHT >= BALL_SIZE, "The player height can not be smaller than the ball size.");
console.assert(PLAYER_WIDTH >= BALL_SIZE, "The player width can not be smaller than the ball size.");
